In [ ]:
from qutip import * # qutip == 5.0.4
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Hamiltonian
$$\begin{align}​
H(t) &= \sum_{i = j}^{n} \frac{\Omega_j(t)}{2} |1\rangle_j {}_j\langle r| + \text{h.c.} \\​
&+ \sum_{j <> k} B_{jk} |rr\rangle_{jk} {}_{jk}\langle rr|.​
\end{align}$$

In [25]:
# Define the parameters
N = 1000 # time steps
T = 1.0 # total time
t = np.linspace(0, T, N) # time array
Omega_max = 10

# the Two Qubit System with Infinte Blockade Strength

In [ ]:
n = 2 # number of qubits
dim = 3 # 3 levels for each qubit

# Initialize the state
qubit1 = Qobj([[0],[1],[0]]) # first qubit
qubit2 = Qobj([[1],[1],[0]]) # second qubit
joint_state = tensor(qubit1, qubit2) # joint state of the two qubits

Omega = np.zeros(N) # Global Pulse so Omega_1 = Omega_2 = Omega
qubit1,qubit2,joint_state

(Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [1.]
  [0.]],
 Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
 Qobj data =
 [[1.]
  [1.]
  [0.]],
 Quantum object: dims=[[3, 3], [1, 1]], shape=(9, 1), type='ket', dtype=Dense
 Qobj data =
 [[0.]
  [0.]
  [0.]
  [1.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]])